config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end

  namespace :trainers_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  
  devise_for :trainers
  
  resources :teams
    
  resources :pokemon, only: [:index]

  get '/home', to: 'site/welcome#index'

  root to: 'site/welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :trainer

  
end

app/models/trainer.rb
class Trainer < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_one :trainer_profile
accepts_nested_attributes_for :trainer_profile, reject_if: :all_blank
has_many :teams
  
end

app/models/trainer_profile.rb
class TrainerProfile < ApplicationRecord
  belongs_to :trainer
  has_one_attached :avatar

  
  # Virtual attributes
  def full_name
    [self.first_name, self.last_name].join(' ')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end

end

app/controllers/pokemon_controller.rb
class PokemonController < TrainersBackofficeController
  def index
    pokemon = params[:pokemon]
    @pokemon = PokeFacade.get_a_pokemon(pokemon)
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/teams_controller.rb
class TeamsController < TrainersBackofficeController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all.page(params[:page])
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)
    @team.trainer_id = current_trainer.id

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_path, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to teams_path, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name, :trainer_id)
    end
end

app/controllers/trainers_backoffice/profile_controller.rb
class TrainersBackoffice::ProfileController < TrainersBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_trainer
  
  def edit
    @trainer.build_trainer_profile if @trainer.trainer_profile.blank?
  end

  def update
    if @trainer.update(trainer_params)
      bypass_sign_in(@trainer)
      unless trainer_params[:trainer_profile_attributes][:avatar]
        redirect_to trainers_backoffice_profile_path, notice: 'Treinador atualizado com sucesso!'
      end
    else
      render :edit
    end
  end

  private

  def set_trainer
    @trainer = Trainer.find(current_trainer.id)
  end

  def trainer_params
    params.require(:trainer).permit(:email, :password, :password_confirmation, trainer_profile_attributes: [:id, :first_name, :last_name, :age, :gender, :birthdate, :avatar])
  end

  def verify_password
    if params[:trainer][:password].blank? && params[:trainer][:password_confirmation].blank?
      params[:trainer].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/trainers_backoffice/welcome_controller.rb
class TrainersBackoffice::WelcomeController < TrainersBackofficeController
  
  def index
  end
end

app/controllers/trainers_backoffice_controller.rb
class TrainersBackofficeController < ApplicationController
  before_action :authenticate_trainer!
  before_action :build_profile
  layout 'trainers_backoffice'

  private

  def build_profile
    current_trainer.build_trainer_profile if current_trainer.trainer_profile.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trainers_backoffice/profile_helper.rb
module TrainersBackoffice::ProfileHelper
  def gender_select(trainer, current_gender)
    trainer.trainer_profile.gender == 'M' ? 'btn-primary' : 'btn-default'
  end
end

app/helpers/trainers_backoffice/welcome_helper.rb
module TrainersBackoffice::WelcomeHelper
end

app/helpers/trainers_backoffice_helper.rb
module TrainersBackofficeHelper
  
  def avatar_url
    avatar = current_trainer.trainer_profile.avatar
    avatar.attached? ? avatar : 'img.jpg'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocketMonster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Victor Guedes">

    <title>PocketMonster</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'site' %>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/navbars/">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    <br>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded">
        <a class="navbar-brand" href="#">Pocket Monster</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
          </ul>
          <form class="form-inline my-2 my-md-0">
            <% unless trainer_signed_in? %>
              <%= link_to 'Entrar', new_trainer_session_path, class:"nav-link" %>
              <%= link_to 'Cadastrar-se', new_trainer_registration_path, class:"nav-link" %>
            <% else %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= current_trainer.email %> </a>
                <div class="dropdown-menu" aria-labelledby="dropdown09">
                  <%= link_to trainers_backoffice_welcome_index_path, class:"dropdown-item" do %>
                    <i class="fas fa-user mr-2"></i> Perfil
                  <% end %>
                  <hr class="navbar-divider">
                  <%= link_to destroy_trainer_session_path, class:"dropdown-item", method: :delete do %>
                    <i class="fas fa-sign-out-alt fa-fw mr-2"></i> Sair
                  <% end %>
                </div>
              </li>
            <% end %>
          </form>
        </div>
      </nav>

      <main role="main">
        <div class="jumbotron">
          <div class="col-sm-8 mx-auto">
              <%= yield %>
            </p>
          </div>
        </div>
      </main>
     
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>

    <% if notice %>
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
        ele: 'body', // which element to append to
        type: 'info', // (null, 'info', 'error', 'success')
        offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
        align: 'right', // ('left', 'right', or 'center')
        allow_dismiss: true,
        stackup_spacing: 10 // spacing between consecutively stacked growls.
        });
      <% end %>
    <% end %> 
  </body>
</html>

app/views/layouts/trainer_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="Victor Guedes" content="">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'trainer_devise' %>
  </head>

  <body class="bg-gradient-primary">
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'trainer_devise' %>

    <% unless resource.errors.empty? %>
      <% resource.errors.full_messages.each do |msg| %>
        <%= javascript_tag do %>
          $.bootstrapGrowl('<%= msg %>', {
          ele: 'body', // which element to append to
          type: 'info', // (null, 'info', 'error', 'success')
          offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
          align: 'right', // ('left', 'right', or 'center')
          allow_dismiss: true,
          stackup_spacing: 10 // spacing between consecutively stacked growls.
          });
        <% end %>
      <% end %>
    <% end %> 
  </body>
</html>

app/views/layouts/trainers_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pocket Monster</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'trainers_backoffice' %>
  </head>

  <body id="page-top">
    <div id="wrapper">
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <div class="nav-item p-4">
          <li class="d-flex justify-content-center">
            <%= link_to image_tag(avatar_url, alt:"...", class:"img-profile rounded-circle", style:"width: 60px", id: "imgAvatarMd"), '#', "data-toggle":"modal", "data-target":"#avatarModal" %>
            <span class="d-flex align-items-center text-gray-100 pl-3"> <%= current_trainer.trainer_profile.full_name %> </span> 
          </li>
        </div>

        <hr class="sidebar-divider">

        <li class="nav-item">
          <%= link_to trainers_backoffice_profile_path, class: "nav-link" do %>
            <i class="fas fa-id-card"></i> Profile
          <% end %>
        </li>

        <hr class="sidebar-divider">

        <li class="nav-item">
          <%= link_to teams_path, class: "nav-link" do %>
            <i class="fas fa-gamepad"></i> Teams
          <% end %>
        </li>

        <hr class="sidebar-divider">

        <li class="nav-item">
          <%= link_to trainers_backoffice_welcome_index_path, class: "nav-link" do %>
            <i class="fas fa-dragon"></i> PokeDex
          <% end %>
        </li>

      </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>
            
            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              
              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-bell fa-fw"></i>
                  <!-- Counter - Alerts -->
                  <span class="badge badge-danger badge-counter">3+</span>
                </a>
                <!-- Dropdown - Alerts -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                  <h6 class="dropdown-header">
                      Alerts Center
                  </h6>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-primary">
                          <i class="fas fa-file-alt text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500"> 05 de Outubro, 2021</div>
                      <span class="font-weight-bold">Victor foi contratado como desenvolvedor junior da Maino!</span>
                    </div>
                  </a>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-success">
                          <i class="fas fa-donate text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500">05 de Julho, 2022</div>
                      Victor foi promovido para desenvolvedor pleno!
                    </div>
                  </a>
                  <a class="dropdown-item text-center small text-gray-500" href="#">Mostrar todos os alertas</a>
                </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag avatar_url, alt: '', class:"img-profile rounded-circle", id: "imgAvatarSm" %>
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small pl-2"><%= current_trainer.email %></span>
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                  <%= link_to destroy_trainer_session_path, class:"dropdown-item", method: :delete do %>
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Sair
                  <% end %>
                </div>
              </li>
            </ul>
          </nav>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
          <!-- End of Main Content -->
          <!-- Footer -->
          <footer class="bg-white">
          </footer>
          <!-- End of Footer -->
      </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Modal -->
    <div class="modal fade" id="avatarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
        <%= form_with(url: trainers_backoffice_profile_path, model: current_trainer, class:"form-horizontal form-label-left") do |form| %>
          <div class="modal-header">
              <h3 class="modal-title" id="myModalLabel">Avatar</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <%= form.fields_for :trainer_profile do |profile_form|  %>
              <div class="form-group">
                <%= image_tag(avatar_url, alt:"...", class:"img-profile rounded-circle", style:"width:100px", id:"imgAvatarLg") %>
                <%= profile_form.file_field :avatar %>
              </div>
            <% end %>
            <p>Salve para ver o novo avatar!</p>
          </div>
          <div class="modal-footer">
            <%= form.submit "Salvar", class:"btn btn-primary" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <!-- /Modal -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'trainers_backoffice' %>

    <% if notice %>
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
        ele: 'body', // which element to append to
        type: 'info', // (null, 'info', 'error', 'success')
        offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
        align: 'right', // ('left', 'right', or 'center')
        allow_dismiss: true,
        stackup_spacing: 10 // spacing between consecutively stacked growls.
        });
      <% end %>
    <% end %>
  </body>

</html>

app/views/pokemon/index.html.erb
<div class="result-box">
  <div align="center">
    <h1><%= @pokemon.name %></h1>
  </div>

  <div align="center">
    <p>Número: <%= @pokemon.number %></p>
    <p>Tipo: <%= @pokemon.type %></p>
    <%= image_tag "#{@pokemon.image}" %>
  </div>
  
  <%= form_tag '/pokemon', method: :get do %>
    <div align="center" class="poke-search">
      <p>Procure por outro Pokémon:</p>
      <%= text_field_tag :pokemon %>
      <%= submit_tag "Search" %>
    </div align="center">
  <% end %>
</div>

app/views/site/welcome/index.html.erb
Site em desenvolvimento!

Agradeço a presença e se possível deixe um feedback!

app/views/trainers_backoffice/profile/edit.html.erb
<div class="row">

  <div class="col-lg-12">
    <h1 class="page-header"> <%= @trainer.model_name.human %>  </h1>
  </div>

</div>

<hr class="sidebar-divider">

<% if @trainer.errors.any? %>
  <div class="alert alert-danger alert-dismissable col-lg-6">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <ul>
      <% @trainer.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        Informações
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-12">

            <%= form_with(url: trainers_backoffice_profile_path, model: @trainer, local: true) do |form| %>
 
              <div class="form-group">
                <%= form.label :email %>
                <%= form.email_field :email, class:"form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :password %>
                <%= form.password_field :password, class:"form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :password_confirmation %>
                <%= form.password_field :password_confirmation, class:"form-control" %>
              </div>

              <%= form.fields_for :trainer_profile do |profile_form| %>
                <div class="form-group">
                  <%= profile_form.label :first_name %>
                  <%= profile_form.text_field :first_name, class:"form-control" %>
                </div>

                <div class="form-group">
                  <%= profile_form.label :last_name %>
                  <%= profile_form.text_field :last_name, class:"form-control" %>
                </div>

                <div class="form-group">
                  <%= profile_form.label :gender, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <div id="gender" class="btn-group" data-toggle="buttons">
                      <label class="btn <%= gender_select(@trainer, 'M') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-light">
                        <%= profile_form.radio_button :gender, "M", "data-parsley-multiple":"gender"%> &nbsp; Masculino &nbsp;
                      </label>
                      <label class="btn <%= gender_select(@trainer, 'F') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-light">
                        <%= profile_form.radio_button :gender, "F", "data-parsley-multiple":"gender"%> &nbsp; Feminino &nbsp;
                      </label>
                    </div>
                  </div>
                </div>

                <%= javascript_tag do %>
                  var labels = document.querySelectorAll('div#gender label');

                  labels.forEach((label) => {
                    label.addEventListener('click', () => {
                      label.classList.remove('btn-light');
                      label.classList.add('btn-primary');

                      labels.forEach((lbl) => {
                        if(lbl !== label){
                          lbl.classList.remove('btn-primary');
                          lbl.classList.add('btn-light');
                        };
                      });
                    });
                  });
                <% end %>

                <div class="form-group">
                  <%= profile_form.label :age %>
                  <%= profile_form.text_field :age, class:"form-control" %>
                </div>
                
                <div class="form-group">
                  <%= profile_form.label :birthdate %>
                  <%= profile_form.date_field :birthdate, class:"form-control" %>
                </div>
              <% end %>
              <button type="submit" class="btn btn-primary"><%= t('buttons.save') %></button>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainers_backoffice/profile/update.js.erb
$('#avatarModal').modal('hide');

document.getElementById('imgAvatarLg').src = "<%= url_for(@trainer.trainer_profile.avatar) %>"
document.getElementById('imgAvatarMd').src = "<%= url_for(@trainer.trainer_profile.avatar) %>"
document.getElementById('imgAvatarSm').src = "<%= url_for(@trainer.trainer_profile.avatar) %>"

$.bootstrapGrowl('Avatar atualizado com sucesso', {
  ele: 'body', // which element to append to
  type: 'info', // (null, 'info', 'error', 'success')
  offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
  align: 'right', // ('left', 'right', or 'center')
  allow_dismiss: true,
  stackup_spacing: 10 // spacing between consecutively stacked growls.
});

app/views/trainers_backoffice/welcome/index.html.erb
<body>
  <div align'"center class="search-box">
    <div align="center" class="poke-title">
      <h1>PokéDex</h1>
    </div align="center">

    <div align="center" class="poke-form">
      <p>Procure por nome ou número:</p>
      <%= form_tag '/pokemon', method: :get do %>
        <div align="center" class="poke-search">
          <%= text_field_tag :pokemon %>
          <%= submit_tag "Search" %>
        </div align="center">
      <% end %>
    </div align="center">
  </div>
</body>